- book:
    name: 'Roboto Slab'
    tile:
      - 'refined-hazard-concrete-left'
      - 'hazard-concrete-left'
      - 'stone'
    font:
      - family: 'Roboto Slab'
        weight:
          - 'Thin'
          - 'Regular'
          - 'Bold'
          - 'Black'
        size: [8, 9, 10, 11, 12, 14, 16, 18, 20, 24, 28, 32, 48, 64]

- blueprint:
    name: 'Roboto Slab'
    text: |
      ABCDEFGHIJKLMNOPQRSTUVWXYZ
      1234567890
      ,.?!:;\'"()[]{}/*+-=><&$%^|#@\_~`

      THE (QUICK, BROWN) FOX JUMPS
      OVER THE [BORED & LAZY] DOG!

      WHAT IS 30% OF $23.75?

        1 + 2 = 3
       10 - 1 = 9
       3.14159
    tile:
      - 'refined-hazard-concrete-left'
    font:
      - family: 'Roboto Slab'
        weight:
          - 'Thin'
          - 'Regular'
          - 'Bold'
          - 'Black'
        size: [8, 9, 10, 11, 12, 14, 16, 18, 20, 24, 28, 32, 48, 64]
