fonts:
  - family: 'Roboto Slab'
    faces:
      - weight: 'Black'
        file: 'Roboto_Slab/static/RobotoSlab-Black.ttf'
      - weight: 'ExtraBold'
        file: 'Roboto_Slab/static/RobotoSlab-ExtraBold.ttf'
      - weight: 'Bold'
        file: 'Roboto_Slab/static/RobotoSlab-Bold.ttf'
      - weight: 'SemiBold'
        file: 'Roboto_Slab/static/RobotoSlab-SemiBold.ttf'
      - weight: 'Medium'
        file: 'Roboto_Slab/static/RobotoSlab-Medium.ttf'
      - weight: 'Regular'
        file: 'Roboto_Slab/static/RobotoSlab-Regular.ttf'
      - weight: 'Light'
        file: 'Roboto_Slab/static/RobotoSlab-Light.ttf'
      - weight: 'ExtraLight'
        file: 'Roboto_Slab/static/RobotoSlab-ExtraLight.ttf'
      - weight: 'Thin'
        file: 'Roboto_Slab/static/RobotoSlab-Thin.ttf'
